services:
    service_registry:
        build:
            context: ../
            dockerfile: ./service_registry/Dockerfile
        environment:
            SERVICE_REGISTRY_IP: localhost
            SERVICE_REGISTRY_PORT: :7777
        ports:
            - 7777:7777
