services:
  service_registry:
    build:
      context: ../
      dockerfile: ./service_registry/Dockerfile
    environment:
      SERVICE_REGISTRY_IP: 127.0.0.1
      SERVICE_REGISTRY_PORT: :7777
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost:7777/health']
      interval: 3s
      timeout: 3s
      retries: 3
    ports:
    - 7777:7777
